In [1]:
import numpy as np

# Use the following code for the questions below:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
print(type(a))

<class 'numpy.ndarray'>


### 1 How many negative numbers are there?


In [2]:
# There are 4 negative numbers

sum(a < 0)

4

### 2 How many positive numbers are there? 

In [3]:
# There are 5 positive numbers

sum(a > 0)

5

### 3 How many even numbers are there?

In [4]:
# There are 8 even numbers

sum(a % 2 == 0)

8

### 4 If you were to add 3 to each data point, how many positive numbers would there be?

In [5]:
# if you added 3 to each data point, there would be 10 positive numbers
sum((a + 3) > 0)

10

### 5 If you squared each number, what would the new mean and standard deviation be?

In [6]:
aa = a**2
aa

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [7]:
# The new median would be 12.5
np.median(aa)

12.5

In [8]:
# New mean == 74
aa.mean()

74.0

In [9]:
# New standar diviation 144.0243035046516
aa.std()

144.0243035046516

### 6 Acommon statistical operation on a dataser is centering. This means to adjust the data such thath mean of the data is 0.  This is done by substracting the mean from each data point. Center the data set.

In [10]:
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7 Calculate the z-score for each data point. Recall that the z-score is given by:

Z = (x − μ) / σ

In [11]:
import pandas as pd
import scipy.stats as stats

In [12]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

###  8 Copy the setup and exrcise directions from More Numpy Practice

In [13]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]



# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]


In [14]:
a = np.array(a)
a = np.array(b)

In [15]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
# The sum is  == 33
sum_of_a = a.sum()
sum_of_a

33

In [16]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
# Min = 3
min_of_a = a.min()
min_of_a

3

In [17]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
# Max = 8
max_of_a = a.max()
max_of_a

8

In [18]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
# Average = 5.5
mean_of_a = a.mean()
mean_of_a

5.5

In [19]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
# product_of_a
product_of_a = a.prod()
product_of_a

20160

In [20]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = a**2


In [21]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
