In [1]:
import numpy as np

# Use the following code for the questions below:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
print(type(a))

<class 'numpy.ndarray'>


### 1 How many negative numbers are there?


In [2]:
# There are 4 negative numbers

sum(a < 0)

4

### 2 How many positive numbers are there? 

In [3]:
# There are 5 positive numbers

sum(a > 0)

5

### 3 How many positive even numbers are there?

In [36]:
# There are 8 even numbers

sum(a % 2 == 0)

5

### 4 If you were to add 3 to each data point, how many positive numbers would there be?

In [5]:
# if you added 3 to each data point, there would be 10 positive numbers
sum((a + 3) > 0)

10

### 5 If you squared each number, what would the new mean and standard deviation be?

In [6]:
aa = a**2
aa

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [7]:
# The new median would be 12.5
np.median(aa)

12.5

In [8]:
# New mean == 74
aa.mean()

74.0

In [9]:
# New standar diviation 144.0243035046516
aa.std()

144.0243035046516

### 6 Acommon statistical operation on a dataser is centering. This means to adjust the data such thath mean of the data is 0.  This is done by substracting the mean from each data point. Center the data set.

In [10]:
a - a.mean()

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7 Calculate the z-score for each data point. Recall that the z-score is given by:

Z = (x − μ) / σ

In [11]:
import pandas as pd
import scipy.stats as stats

In [12]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

###  8 Copy the setup and exrcise directions from More Numpy Practice

## Setup 1

In [13]:
# Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
a = np.array(a)

In [15]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
# The sum is  == 55
sum_of_a = a.sum()
sum_of_a

55

In [16]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
# Min = 1
min_of_a = a.min()
min_of_a

1

In [17]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
# Max = 10
max_of_a = a.max()
max_of_a

10

In [18]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
# Average = 5.5
mean_of_a = a.mean()
mean_of_a

5.5

In [19]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
# product_of_a == 3628800
product_of_a = a.prod()
product_of_a

3628800

In [25]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [27]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
# [1, 3, 5, 7, 9]
odds_in_a = a[a%2==1]
odds_in_a

array([1, 3, 5, 7, 9])

In [28]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a[a%2==0]
evens_in_a

array([ 2,  4,  6,  8, 10])

## Setup 2 

In [33]:
## Setup 2: 
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = np.array(b)

In [30]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
# Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [71]:
print(f"b.sum() == {b.sum()}")
print(f"b.min() == {b.min()}")
print(f"b.max == {b.max()}")
print(f"b.avg == {(b.sum()).astype(int)/(b.sum(b < 0)).astype(int)}")
print(f"b.squares() == {b**2}")

b.sum() == 33
b.min() == 3
b.max == 8


TypeError: only integer scalar arrays can be converted to a scalar index

In [59]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)
    

In [61]:
# 9
b.shape

(2, 3)

In [62]:
#10 
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [41]:
# 11
b.flatten()

array([3, 4, 5, 6, 7, 8])

In [42]:
# reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

## Setup 3 

In [46]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# Exercise 1 - Find the min, max, sum, and product of c.
print(f"min of c = {c.min()}")
print(f"max of c = {c.max()}")
print(f"sum of c = {c.sum()}")
print(f"product of c = {np.product(c)}")

min of c = 1
max of c = 9
sum of c = 45
product of c = 362880


In [72]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [73]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [76]:
# Exercise 4 - Print out the shape of the array
c.shape

(3, 3)

In [80]:
# Exercise 5 - Transpose c and print out transposed result.
c.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [94]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [92]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
trans = c*c.transpose()
trans

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [93]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
trans.prod()

131681894400

## Setup 4

In [44]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

In [96]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [98]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [99]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [102]:
# Exercise 4 - Find all the negative numbers in d
d[d<0]

array([-90, -30, -45, -45])

In [103]:
# Exercise 5 - Find all the positive numbers in d
d[d>0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [112]:
# Exercise 6 - Return an array of only the unique numbers in d
unique = np.unique(d)
unique

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [114]:
# Exercise 7 - Determine how many unique numbers there are in d
unique.size

11

In [116]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [118]:
# Exercise 9 - Transpose and then print out the shape of d.
transd = d.transpose()
transd.shape

(6, 3)

In [119]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])